version: '3'
services:
  fetch:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: tinvest_perevalov_fetch
    command: python fetch.py
    volumes:
      - ../data:/data
  trade:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: tinvest_perevalov_trade
    command: python trade.py
    volumes:
      - ../data:/data